config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  get 		'/signup',		to: "customers#new"
  get 		'/login', 		to: "sessions#new"
  post 		'login',			to: "sessions#create"
 	delete 	'logout', 	to: "sessions#destroy"
  resources :products
  resources :categories
  resources :customers
  resources :inventories

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product

  validates :quantity_in_stock, presence: true, numericality: true
  validates :sales, presence: true, numericality: true
  validates :product_id, presence: true, uniqueness: true, on: :create
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
	 before_action :set_inventory, only: [:edit, :update, :show, :destroy]

	def index
		@inventories = Inventory.paginate(page: params[:page], per_page: 25)
	end


	def new
		@inventory = Inventory.new
	end

	def create
		@inventory = Inventory.new(inventory_params)
		if @inventory.save
			flash[:success] = "Inventory amount successfully added"
			redirect_to inventories_path
		else
			render 'new'
		end
	end

	def show
	end

	def update
		if @inventory.update_attributes(inventory_params)
			flash[:success] = "Inventory successfully updated"
			redirect_to inventories_path
		else
			render 'edit'
		end
	end

	def destroy
		@inventory.destroy
		flash[:danger] = "Inventory successfully purged"
		redirect_to inventories_path
	end
	
end

  private
 
  def inventory_params
  	params.require(:inventory).permit(:product_id, :quantity_in_stock, :sales)
  end

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end
 

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_inventory_form.html.erb
<div class="form-group">
	<%= simple_form_for @inventory do |f| %>
		<%= f.error_notification %>
		<%= f.input :product_id, collection: Product.all, label_method: :title, value_method: :id, include_blank: false %>
		<%= f.input :quantity_in_stock %>
		<%= f.input :sales %>
		<%= f.button :submit, class: "btn-primary" %>
	<% end %>
</div>

app/views/inventories/edit.html.erb
<div class="container">
	<h3 align="center" class="header">Update Product Inventory</h3>
	<%= render 'inventory_form' %>
</div>

app/views/inventories/index.html.erb
<div class="container">
	<h1 align="center" class="header">Listing all product inventories</h1>
  <div align="center" >
    <div class="page_info">
      <%= page_entries_info @inventories %>
    </div>
    <div align="center">
    	<%= will_paginate @inventories %>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3">
  <% @inventories.each do |inventory| %>
		  <div class="col mb-4 border-info">
		    <div class="card border-info">
		      <div class="card-body">
		        <h5 class="card-title"><%= link_to inventory.product.title, inventory.product %></h5>
		        <hr>
		        <p class="card-text">Quantity in stock : <%= inventory.quantity_in_stock %></p>
		        <p class="card-text">Sales : <%= inventory.sales %></p>
		        <%= link_to "Update inventory", edit_inventory_path(inventory), class: "btn btn-primary" %>
		        <%= link_to "Delete inventory", inventory_path(inventory), method: :delete, class: "btn btn-danger",
		        																data: { confirm: "Are you sure ?"} %>
		      </div>
		    </div>
		  </div>
		<% end %>
	</div>
	<div align="center">
    <%= will_paginate @inventories %>
	</div>
</div>

app/views/inventories/new.html.erb
<div class="container">
	<h3 align="center" class="header">Add Product Quantities</h3>
	<%= render 'inventory_form' %>
</div>