config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  get 		'/signup',		to: "customers#new"
  get 		'/login', 		to: "sessions#new"
  post 		'login',			to: "sessions#create"
 	delete 	'logout', 	to: "sessions#destroy"
  resources :products
  resources :categories
  resources :customers
  resources :inventories

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	before_save {self.category_name = category_name.capitalize }
	validates :category_name, presence: true, length: {minimum: 3},
						uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, except: [:new, :create, :index]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "#{@category_name} successfully created"
			redirect_to category_path(@category)
		else
			render 'new'
		end
	end

	def show
   
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category successfully updated!"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = "category destroyed successfully!"
    redirect_to categories_path
  end	


	private

	def category_params
		params.require(:category).permit(:category_name)
	end

	def set_category
		@category = Category.find(params[:id])
	end

	
end

app/views/categories/_category_form.html.erb
<div class="form-group">
	<%= simple_form_for @category do |f| %>
		<%= f.error_notification %>
		<%= f.input :category_name %>
		<%= f.button :submit, class: "btn-primary" %>
	<% end %>
</div>

app/views/categories/edit.html.erb
<div class="container">
	<h3 align="center" class="header">Edit Category</h3>
	<%= render 'category_form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
	<h1 align="center" class="header">Listing all categories</h1>
	<div class="row row-cols-1 row-cols-md-3">
		<% @categories.each do |category| %>
		  <div class="col mb-4 border-info">
		    <div class="card border-info">
		      <!-- <img src="..." class="card-img-top" alt="..."> -->
		      <div class="card-body">
		        <h5 class="card-title"><%= link_to category.category_name, category %></h5>
		      </div>
		    </div>
		  </div>
		<% end %>
	</div>
</div>

app/views/categories/new.html.erb
<div class="container">
	<h3 align="center" class="header">Add New Category</h3>
	<%= render 'category_form' %>
</div>

app/views/categories/show.html.erb
<div class="container">
	<div class="card">
	  <div class="card-body">
	    <h5 class="card-title row">
	    	<div class="col-2">Category Name:</div>
	    	<div class="col-8"><%= @category.category_name %></div>
	    </h5>
	    <hr>
	    <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-info" %>
	    <%= link_to "Delete this product", category_path(@category), class: "btn btn-danger",
	    			method: :delete, data: { confirm: "Are you sure ?"} %>
	  </div>
	</div>
	<table class="table table-bordered">
		<thead>
			<tr>
  			<th scope="col">CPI</th>
  			<th scope="col">Product title</th>
  			<th scope="col">Actor</th>
  			<th scope="col">Special</th>
			</tr>
		</thead>
		<% @category.products.each do |product| %>
		<tbody>
 			<tr>
	      <td><%= product.common_product_id %></td>
	      <td><%= link_to product.title, product %></td>
	      <td><%= product.actor %></td>
	      <td><%= product.special %></td>
	    </tr>
		</tbody>
		<% end %>
	</table>
	
</div>