config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  get 		'/signup',		to: "customers#new"
  get 		'/login', 		to: "sessions#new"
  post 		'login',			to: "sessions#create"
 	delete 	'logout', 	to: "sessions#destroy"
  resources :products
  resources :categories
  resources :customers
  resources :inventories

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :reorders
	validates :title, presence: true
	validates :actor, presence: true
	validates :description, presence: true, length: {minimum: 10}
	validates :price, presence: true, numericality: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :show, :destroy] 
  
  def index
    @products = Product.paginate(page: params[:page], per_page: 21).order("created_at DESC")
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product successfully added!"
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def show
   
  end

  def edit

  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product successfully updated!"
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:danger] = "Product destroyed successfully!"
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :actor, :price, :special, :common_product_id, :category_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

end

app/helpers/products_helper.rb
module ProductsHelper
	
end

app/views/products/_form.html.erb
<div class="form-group">
	<%= simple_form_for @product do |f| %>
		<%= f.error_notification %>
		<%= f.input :title %>
		<%= f.input :description %>
		<%= f.input :actor %>
		<%= f.input :price %>
		<%= f.input :special %>
		<%= f.input :common_product_id %>
		<%= f.input :category_id, collection: Category.all, label_method: :category_name, value_method: :id, include_blank: false %>
		<%= f.button :submit, class: "btn-primary" %>
	<% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
	<h3 align="center" class="header">Edit Product</h3>
	<%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="container">
	<h1 align="center" class="header">Listing all products</h1>
  <div align="center" >
    <div class="page_info">
      <%= page_entries_info @products %>
    </div>
    <div align="center">
    	<%= will_paginate @products %>
    </div>
  </div>
	<div class="row row-cols-1 row-cols-md-3">
		<% @products.each do |product| %>
		  <div class="col mb-4 border-info">
		    <div class="card border-info">
		      <!-- <img src="..." class="card-img-top" alt="..."> -->
		      <div class="card-body">
		        <h5 class="card-title"><%= link_to product.title, product %></h5>
		        <p class="card-text"><%= truncate(product.description, :length => 50) %>
		        	<span class="small"><%= link_to "read more", product %></span>
		        </p>
		        
		        <p class="card-text">
		        	<span><em>
		        		<% if product.category.blank? %>
		        			No category mentioned
		        		<% else %>
		        			<%= link_to product.category.category_name, product.category %>
		        		<% end %>
		        			</em></span>
		        </p>
		        <p class="primary">Regular Price: <%= number_to_currency product.price %></p>
		        <% if product.special %>
		            <p class="success">Special Price: <%= number_to_currency product.special %></p>
		        <% else %>
		        	<p class="danger">No Special Pricing Available</p>
		        <% end %>
						
						<%= form_tag order_items_path do %>
							<%= hidden_field_tag :product_id, product.id %>
							<%= number_field_tag :quantity, 1, class: "form-control" %>
							<%= submit_tag "Add to Cart", class: "btn btn-secondary" %>
						<% end %>
		      </div>
		    </div>
		  </div>
		<% end %>
	</div>
	<div align="center">
    <%= will_paginate %>
	</div>
</div>

app/views/products/new.html.erb
<div class="container">
	<h3 align="center" class="header">Add New Product</h3>
	<%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="card">
	  <div class="card-body">
	    <h5 class="card-title row">
	    	<div class="col-2">Product:</div>
	    	<div class="col-8"><%= @product.title %></div>
	    </h5>
	    <div class="row">
	    	<div class="col-2">Description:</div>
	    	<div class="col-10"><%= @product.description %></div>
	    </div>
	    <div class="row">
	    	<div class="col-2">Actor:</div>
	    	<div class="col-10"><%= @product.actor %></div>
	    </div>
	    <div class="row">
	    	<div class="col-2">Regular price:</div>
	    	<div class="col-8"><%= @product.price %></div>
	    </div>
	    <div class="row">
	    	<div class="col-2">Special price:</div>
	    	<div class="col-8"><%= @product.special %></div>
	    </div>
	    <div class="row">
	    	<div class="col-2">CPI:</div>
	    	<div class="col-8"><%= @product.common_product_id %></div>
	    </div>
	    <hr>
	    <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-info" %>
	    <%= link_to "Delete this product", product_path(@product), class: "btn btn-danger",
	    			method: :delete, data: { confirm: "Are you sure ?"} %>
	  </div>
	</div>
</div>