config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  get 		'/signup',		to: "customers#new"
  get 		'/login', 		to: "sessions#new"
  post 		'login',			to: "sessions#create"
 	delete 	'logout', 	to: "sessions#destroy"
  resources :products
  resources :categories
  resources :customers
  resources :inventories

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-offset-2">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">x</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
		<%= link_to "Products", root_path, class: "navbar-brand" %>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mr-auto">
			    <li class="nav-item">
			    	<%= link_to "Products", products_path, class: "nav-link" %>
			    </li>
			    <li class="nav-item">
			      <%= link_to "Categories", categories_path, class: "nav-link" %>
			    </li>
			    <li class="nav-item">
			      <%= link_to "Inventories", inventories_path, class: "nav-link" %>
			    </li>
					<li class="nav-item">
						<%= link_to pluralize(current_cart.items_count, 'item'), cart_path, class: "nav-link" %>
					</li>
			    <li class="nav-item">
			    	<% if !logged_in? %>
			      	<%= link_to "Sign Up!", signup_path, class: "nav-link", tabindex:"-1" %>
			      <% end %>	
			    </li>
			  </ul>
				<ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>

			    <li class="nav-item dropdown">
			      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			        <%= current_customer.first_name %>
			      </a>
			      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			        <%= link_to "Settings", edit_customer_path(current_customer), class: "dropdown-item" %>
			        <%= link_to "Show profile", customer_path(current_customer), class: "dropdown-item" %>
			        <div class="dropdown-divider"></div>
			        <%= link_to "Log Out", logout_path, method: :delete, class: "dropdown-item" %>
			      </div>
			    <% else %>
			    		<%= link_to "Login", login_path, class: "dropdown-item" %>
			    </li>
			    <% end %>
			    
			  </ul>
			</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>